name: Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GIN_MODE: test
      config: ../../cmd/config/
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21
        cache-dependency-path: |
              go.sum

    - name: Run Unit Test
      run: go test ./test/... -json > TestResults-${{ github.sha }}.json

    - name: Stop if tests fail
      if: ${{ failure() }}
      run: exit 1

    - name: Upload Go test results
      uses: actions/upload-artifact@v3
      with:
        name: Go-results-${{ github.sha }}
        path: TestResults-${{ github.sha }}.json

    - name: Build Go application
      run: go build -o backend ./cmd/.

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        # username: yohansutanto5
        # password: dckr_pat_TF15zyPxf2b5W29ktP8IekgfsNE

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./cmd/Dockerfile  # Adjust the path to your Dockerfile
        push: true
        tags: |
          yohansutanto5/backend:latest
          yohansutanto5/backend:${{ github.sha }}